apiVersion: v1
kind: Secret
type: Opaque
metadata: 
 name: cribl-config-{{ include "cribl.fullname" . }}
stringData: 
{{- if  .Values.config.license }}
  licenses.yml: |
    licenses:
      - {{ .Values.config.license }}
{{- end }}

{{- if .Values.config.adminPassword }}
  users.json: |
    {"username":"admin","first":"admin","last":"admin","email":"admin","password":"{{ .Values.config.adminPassword }}"}

{{- end }}

{{- if .Values.config.groups }}
  groups.yml: |
{{- range  .Values.config.groups }}
    {{ . }}: {}
{{- end }}
    default:
      description: Default Worker Group
      tags: default

  mappings.yml: |
    rulesets:
      default:
        conf:
          functions:
          {{- range  .Values.config.groups }}
            - filter: cribl.tags.includes('{{ . }}')
              conf:
                add:
                  - name: groupId
                    value: "'{{ . }}'"
              id: eval
              final: true
              description: {{ . }}
  
          {{- end }}
            - filter: "!cribl.group"
              id: eval
              description: Default Mappings
              disabled: false
              final: true
              conf:
                add:
                  - name: groupId
                    value: "'default'"


{{- end }}

  {{- $proto := "tcp" }}
  {{- $group := "" }}
  {{- $tlsopts := "" }}
  {{- if .Values.config.tlsLeader.enable }}
    {{- $proto = "tls" -}}
    {{- if .Values.config.tlsLeader.privKeyPath }}
      {{- $tlsopts = printf "%s&tls.privKeyPath=%s" $tlsopts .Values.config.tlsLeader.privKeyPath }}
    {{- end }}
    {{- if .Values.config.tlsLeader.passphrase }}
      {{- $tlsopts = print $tlsopts "&tls.passphrase=" .Values.config.tlsLeader.passphrase }}
    {{- end }}
    {{- if .Values.config.tlsLeader.capath }}
      {{- $tlsopts = print $tlsopts "&tls.capath=" .Values.config.tlsLeader.capath }}
    {{- end }}
    {{- if .Values.config.tlsLeader.certpath }}
      {{- $tlsopts = printf "%s&tls.certpath=%s" $tlsopts .Values.config.tlsLeader.certpath }}
    {{- end }}
    {{- if .Values.config.tlsLeader.rejectUnauthorized }}
      {{- $tlsopts = printf "%s&tls.rejectUnauthorized=%s" $tlsopts .Values.config.tlsLeader.rejectUnauthorized }}
    {{- end }}
    {{- if .Values.config.tlsLeader.requestCert }}
      {{- $tlsopts = printf "%s&tls.requestCert=%s" $tlsopts .Values.config.tlsLeader.requestCert }}
    {{- end }}
    {{- if .Values.config.tlsLeader.commonNameRegex }}
      {{- $tlsopts = printf "%s&tls.commonNameRegex=%s" $tlsopts .Values.config.tlsLeader.commonNameRegex }}
    {{- end }}
  {{- end }}
  {{- if .Values.config.tag }}
    {{- $group = .Values.config.tag }}
  {{- else if .Values.config.group }}
    {{- $group = .Values.config.group }}
  {{- end }}
  url-master: "{{ $proto }}://{{ .Values.config.token }}@{{ include "cribl.fullname" . }}-leader-internal:4200?group={{ $group }}&tag={{ $group }}{{ $tlsopts | replace " " "+"}}"
